// Generated by CoffeeScript 1.12.7
(function() {
  var easy, extreme, grades, hard, maps, normal, save, star, table;

  star = '🌟';

  maps = 'Romeo x Cinderella\nMagnet\nAi Kotoba\nSound\nKokoro\nPackaged\nMigikata no Chou\nMarginal\nThe Secret Garden\nJust Be Friends\nStrobo Night\nClover * Club\nFrom Y to Y\nUpdatino Your Love List?\nYellow\nInochi no Uta\nChange Me\nPoPiPo\nCantarella\nWhen the First Love Ends\nKouja to Mori to Mahou no Uta\nDear Cocoa Girls\nGigantic Girl\nDear\nGemini\nVOiCE -DIVA MIX-\nWorld is Mine\nMiracle Paint\nMoon\nVelvet Arabesque\nInnocence\nMeltdown\nHonto wa Wakatteru\nMelt\nLove-colored Ward\nFinder(DSLR remix - re:edit)\nPromise\nBeware of Miku Miku Bacteria\nHajimete no Oto\nHato\n-UNKNOWN1-\n-UNKNOWN2-\nColorful x Melody\nDouble Lariat\n-UNKNOWN3-\n-UNKNOWN4-'.split('\n');

  grades = 'easy normal hard extreme'.split(' ');

  easy = 'easy';

  normal = 'normal';

  hard = 'hard';

  extreme = 'extreme';

  table = Array(maps.length).map(function(e) {
    return Array(4).fill('');
  });

  save = function(song, difficulty) {
    return table[maps.indexOf(song)][grades.indexOf(difficulty)] = star;
  };

  'Romeo x Cinderella\nMagnet\nAi Kotoba\nSound\nKokoro\nPackaged\nMigikata no Chou\nMarginal\nThe Secret Garden\nVelvet Arabesque'.split('\n').forEach(function(e) {
    return save(e, 'easy');
  });

  require('fs').createWriteStream('./index.html').end('<!doctype html>\n<html><head><link rel="stylesheet" href="style.css"></head><body><table>' + (function() {
    var i, j, k, l, ref, ref1, res;
    res = '';
    for (i = k = 0, ref = maps.length; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
      res += '<tr>';
      for (j = l = 0, ref1 = grades.length; 0 <= ref1 ? l < ref1 : l > ref1; j = 0 <= ref1 ? ++l : --l) {
        res += '<td>' + table[i][j] + '</td>';
      }
      res += '</tr>';
    }
    return res;
  })());

  +'</table></body></html>';

}).call(this);
